//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WepDevices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string SerialNo { get; set; }
        public Nullable<System.DateTime> Aqusationdate { get; set; }
        public string Memo { get; set; }
        public Nullable<int> Category_Id { get; set; }
        public Nullable<int> Property_Id { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Property Property { get; set; }
    }
}
