//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WepDevices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Property()
        {
            this.Devices = new HashSet<Device>();
        }
    
        public int Id { get; set; }
        public string DeviceNameProperty { get; set; }
        public string Processor { get; set; }
        public string Dimension { get; set; }
        public string MACAddress { get; set; }
        public string IPAddress { get; set; }
        public string AllowUsb { get; set; }
        public string NetWorkSpeed { get; set; }
        public string OperatingSystem { get; set; }
        public string ports { get; set; }
        public string HD { get; set; }
        public string User_Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Device> Devices { get; set; }
    }
}
